### ISSUE TITLE
Mount `volume` for database in `docker-compose.hornet.yml`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#227]
Right now the database is only stored within the `mongo` container, that might not be persisted. It should probably look something like this:

```yml
mongo:
  image: mongo
  restart: always
  command: --quiet --logpath /dev/null
  volume:
    - ./data:/data/db
```

That would probably also require to set the permissions of the folder on the host.
