### ISSUE TITLE
Enable/disable `api` and `inx` from `config.toml`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#387]
I've talked with @shufps about deployment. To make it easy to deploy Chronicle in a scalable fashion, we need to be able to enable and disable both the `api` and `inx` via the `config.toml` file.

For this, we need to add simple fields:

```toml
[api]
enabled = true
# ...

[inx]
enabled = true
# ...
```

From a DevOps perspective it is much easier to do this via configuration flags, or environment variables then using separate Docker images.
