### ISSUE TITLE
Remove `continue-on-error` from the `docs` job in CI

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#683]
```yml
docs:
    runs-on: ubuntu-latest
    # There is an ICE in rustc nightly which prevents this workflow from running:
    # https://github.com/rust-lang/rust/issues/101844
    # Until this is resolved, we allow this job to fail.
    continue-on-error: true
```

Currently waiting on https://github.com/rust-lang/rust/issues/101844.
